name: 'Cloud auth'
description: 'Authenticate with aws, gcp or azure'
author: 'a5c.ai'
branding:
  icon: 'cpu'
  color: 'blue'

runs:
  using: 'composite'
  steps:
    - name: Setup Cloud CLI Tools
      run: |
        echo "Checking for cloud provider credentials..."
        
        # Check for Azure credentials
        if [[ -n "$AZURE_APPLICATION_CLIENT_ID" && -n "$AZURE_APPLICATION_CLIENT_SECRET" && -n "$AZURE_TENANT_ID" ]]; then
          echo "Azure credentials detected, installing Azure CLI..."
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          
          echo "Logging into Azure..."
          az login --service-principal \
            --username "$AZURE_APPLICATION_CLIENT_ID" \
            --password "$AZURE_APPLICATION_CLIENT_SECRET" \
            --tenant "$AZURE_TENANT_ID"
          echo "Azure CLI authentication successful"
        else
          echo "Azure credentials not found (AZURE_APPLICATION_CLIENT_ID, AZURE_APPLICATION_CLIENT_SECRET, AZURE_TENANT_ID)"
        fi
        
        # Check for AWS credentials
        if [[ -n "$AWS_ACCESS_KEY_ID" && -n "$AWS_SECRET_ACCESS_KEY" ]]; then
          echo "AWS credentials detected, installing AWS CLI..."
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --update
          rm -rf awscliv2.zip aws/
          
          echo "Configuring AWS CLI..."
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          if [[ -n "$AWS_DEFAULT_REGION" ]]; then
            aws configure set default.region "$AWS_DEFAULT_REGION"
          fi
          if [[ -n "$AWS_SESSION_TOKEN" ]]; then
            aws configure set aws_session_token "$AWS_SESSION_TOKEN"
          fi
          
          echo "Testing AWS CLI authentication..."
          aws sts get-caller-identity
          echo "AWS CLI authentication successful"
        else
          echo "AWS credentials not found (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY)"
        fi
        
        # Check for Google Cloud credentials
        if [[ -n "$GOOGLE_APPLICATION_CREDENTIALS" || -n "$GCP_SA_KEY" ]]; then
          echo "Google Cloud credentials detected, installing Google Cloud CLI..."
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update && sudo apt-get install -y google-cloud-cli
          
          if [[ -n "$GCP_SA_KEY" ]]; then
            echo "Using GCP_SA_KEY for authentication..."
            echo "$GCP_SA_KEY" | base64 -d > /tmp/gcp-key.json
            gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
            rm /tmp/gcp-key.json
          elif [[ -n "$GOOGLE_APPLICATION_CREDENTIALS" ]]; then
            echo "Using GOOGLE_APPLICATION_CREDENTIALS for authentication..."
            gcloud auth activate-service-account --key-file="$GOOGLE_APPLICATION_CREDENTIALS"
          fi
          
          if [[ -n "$GCP_PROJECT_ID" ]]; then
            gcloud config set project "$GCP_PROJECT_ID"
          fi
          
          echo "Testing Google Cloud CLI authentication..."
          gcloud auth list
          echo "Google Cloud CLI authentication successful"
        else
          echo "Google Cloud credentials not found (GOOGLE_APPLICATION_CREDENTIALS or GCP_SA_KEY)"
        fi
        
        echo "Cloud CLI setup completed"
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        AZURE_APPLICATION_CLIENT_ID: ${{ env.AZURE_APPLICATION_CLIENT_ID }}
        AZURE_APPLICATION_CLIENT_SECRET: ${{ env.AZURE_APPLICATION_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ env.AZURE_TENANT_ID }}
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
        AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        GCP_SA_KEY: ${{ env.GCP_SA_KEY }}
        GCP_PROJECT_ID: ${{ env.GCP_PROJECT_ID }}
