# Example user configuration for A5C Runner
# This file overrides settings from the built-in default configuration
# Uncomment and modify the sections you want to customize

# Override default settings
# defaults:
#   cli_command: "myagent --model gpt-4 --message {{prompt}}"
#   model: "claude-3-opus-20240229"
#   max_turns: 25
#   timeout: 45

# Override MCP configuration path
# mcp_config_path: ".a5c/custom-mcps.json"

# Override file processing settings
# file_processing:
#   include_patterns:
#     - "src/**/*.ts"
#     - "lib/**/*.js"
#     - "**/*.md"
#   exclude_patterns:
#     - "node_modules/**"
#     - "dist/**"
#     - "*.test.*"

# Enable and configure remote agents (optional)
# NOTE: Remote agents are enabled by default. For private repositories, ensure
# your workflow has the appropriate permissions and GITHUB_TOKEN access.
remote_agents:
  enabled: true
  cache_timeout: 120  # 2 hours
  retry_attempts: 5
  retry_delay: 2000   # 2 seconds
  sources:
    individual:
      - uri: "https://raw.githubusercontent.com/myorg/.a5c/main/agents/custom-agent.agent.md"
        alias: "custom-remote-agent"
      # Example private repository agent:
      # - uri: "https://raw.githubusercontent.com/myorg/private-agents/main/proprietary.agent.md"
      #   alias: "private-agent"
    repositories:
      - uri: "https://github.com/myorg/a5c-for-development"
        pattern: ".a5c/agents/**/*.agent.md"
      # Example private repository:
      # - uri: "https://github.com/myorg/private-agents"
      #   pattern: "agents/**/*.agent.md"

# Override agent discovery settings
# agent_discovery:
#   enabled: true
#   max_agents_in_context: 15
#   include_same_directory: true

# Override prompt URI settings
# prompt_uri:
#   cache_timeout: 120
#   retry_attempts: 5
#   retry_delay: 2000 